USE `es_extended`;

ALTER TABLE `users`
	ADD COLUMN `firstname` VARCHAR(50) NULL DEFAULT '',
	ADD COLUMN `lastname` VARCHAR(50) NULL DEFAULT '',
	ADD COLUMN `dateofbirth` VARCHAR(25) NULL DEFAULT '',
	ADD COLUMN `sex` VARCHAR(10) NULL DEFAULT '',
	ADD COLUMN `height` VARCHAR(5) NULL DEFAULT ''
;
ALTER TABLE `characters`
	ADD COLUMN `identifier` VARCHAR(50) NULL DEFAULT '',
	ADD COLUMN `firstname` VARCHAR(50) NULL DEFAULT '',
	ADD COLUMN `lastname` VARCHAR(25) NULL DEFAULT '',
	ADD COLUMN `dateofbirth` VARCHAR(10) NULL DEFAULT '',
	ADD COLUMN `sex` VARCHAR(5) NULL DEFAULT '',
	ADD COLUMN `height` VARCHAR(5) NULL DEFAULT 
;
